services:
  auto-grader:
    build: .
    container_name: my-auto-grader
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Mount the client secret and token files
      - ./client_secret.json:/app/src/client_secret.json:ro
      - ./token.json:/app/src/token.json
